const BOOK_METADATA = {
  'Genesis': {chapterCount: 50, order: 1},
  'Exodus': {chapterCount: 40, order: 2},
  'Leviticus': {chapterCount: 27, order: 3},
  'Numbers': {chapterCount: 36, order: 4},
  'Deuteronomy': {chapterCount: 34, order: 5},
  'Joshua': {chapterCount: 24, order: 6},
  'Judges': {chapterCount: 21, order: 7},
  'Ruth': {chapterCount: 4, order: 8},
  '1 Samuel': {chapterCount: 31, order: 9},
  '2 Samuel': {chapterCount: 24, order: 10},
  '1 Kings': {chapterCount: 22, order: 11},
  '2 Kings': {chapterCount: 25, order: 12},
  '1 Chronicles': {chapterCount: 29, order: 13},
  '2 Chronicles': {chapterCount: 36, order: 14},
  'Ezra': {chapterCount: 10, order: 15},
  'Nehemiah': {chapterCount: 13, order: 16},
  'Esther': {chapterCount: 10, order: 17},
  'Job': {chapterCount: 42, order: 18},
  'Psalms': {chapterCount: 150, order: 19},
  'Proverbs': {chapterCount: 31, order: 20},
  'Ecclesiastes': {chapterCount: 12, order: 21},
  'Song of Solomon': {chapterCount: 8, order: 22},
  'Isaiah': {chapterCount: 66, order: 23},
  'Jeremiah': {chapterCount: 52, order: 24},
  'Lamentations': {chapterCount: 5, order: 25},
  'Ezekiel': {chapterCount: 48, order: 26},
  'Daniel': {chapterCount: 12, order: 27},
  'Hosea': {chapterCount: 14, order: 28},
  'Joel': {chapterCount: 3, order: 29},
  'Amos': {chapterCount: 9, order: 30},
  'Obadiah': {chapterCount: 1, order: 31},
  'Jonah': {chapterCount: 4, order: 32},
  'Micah': {chapterCount: 7, order: 33},
  'Nahum': {chapterCount: 3, order: 34},
  'Habakkuk': {chapterCount: 3, order: 35},
  'Zephaniah': {chapterCount: 3, order: 36},
  'Haggai': {chapterCount: 2, order: 37},
  'Zechariah': {chapterCount: 14, order: 38},
  'Malachi': {chapterCount: 4, order: 39},
  'Matthew': {chapterCount: 28, order: 40},
  'Mark': {chapterCount: 16, order: 41},
  'Luke': {chapterCount: 24, order: 42},
  'John': {chapterCount: 21, order: 43},
  'Acts': {chapterCount: 28, order: 44},
  'Romans': {chapterCount: 16, order: 45},
  '1 Corinthians': {chapterCount: 16, order: 46},
  '2 Corinthians': {chapterCount: 13, order: 47},
  'Galatians': {chapterCount: 6, order: 48},
  'Ephesians': {chapterCount: 6, order: 49},
  'Philippians': {chapterCount: 4, order: 50},
  'Colossians': {chapterCount: 4, order: 51},
  '1 Thessalonians': {chapterCount: 5, order: 52},
  '2 Thessalonians': {chapterCount: 3, order: 53},
  '1 Timothy': {chapterCount: 6, order: 54},
  '2 Timothy': {chapterCount: 4, order: 55},
  'Titus': {chapterCount: 3, order: 56},
  'Philemon': {chapterCount: 1, order: 57},
  'Hebrews': {chapterCount: 13, order: 58},
  'James': {chapterCount: 5, order: 59},
  '1 Peter': {chapterCount: 5, order: 60},
  '2 Peter': {chapterCount: 3, order: 61},
  '1 John': {chapterCount: 5, order: 62},
  '2 John': {chapterCount: 1, order: 63},
  '3 John': {chapterCount: 1, order: 64},
  'Jude': {chapterCount: 1, order: 65},
  'Revelation': {chapterCount: 22, order: 66}
};

export { BOOK_METADATA };
